# Generated by Django 3.2.4 on 2021-07-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('idContenido', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Contenido')),
                ('tipoContenido', models.CharField(max_length=50, verbose_name='Tipo de Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idnoticia', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Noticia')),
                ('fecha', models.CharField(max_length=10, verbose_name='Fecha')),
                ('region', models.CharField(max_length=30, verbose_name='Region')),
                ('comuna', models.CharField(max_length=30, verbose_name='Comuna')),
                ('descripcion', models.CharField(max_length=1000, null=True, verbose_name='Descripcion de Noticia')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contenido')),
            ],
        ),
    ]
