# Generated by Django 3.2.4 on 2021-07-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Noticia')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=20, verbose_name='Direccion')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('pais', models.CharField(max_length=25, verbose_name='Pais')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='contenido',
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
