# Generated by Django 3.2.4 on 2021-07-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210705_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Email'),
        ),
    ]
