# Generated by Django 3.2.4 on 2021-07-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_colaborador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='contraseña',
            field=models.CharField(max_length=100, null=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='direccion',
            field=models.CharField(max_length=40, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='pais',
            field=models.CharField(max_length=40, verbose_name='Pais'),
        ),
    ]
